---
resource_types:
  - name: docker-open-build-service-resource
    type: docker-image
    source:
        repository: machinerytool/concourse-open-build-service-resource
        tag: latest

jobs:
  #
  # Pipeline won't automatically build if src changes, need to
  # run start-job manually first to unblock the resource
  #
  - name: start-job
    serial: true
    plan:
      - get: src
      - get: ci
      - get: bosh-io-release.bosh
      - get: semver.bosh-stemcell
        params:
          bump: major
      - put: semver.bosh-stemcell
        params:
          file: semver.bosh-stemcell/number

  - name: build-os-image-ubuntu-trusty
    serial_groups: [os-image]
    plan:
      - aggregate:
        - get: src
          passed:
            - start-job
        - get: ci
          passed:
            - start-job
        - put: semver.os-image-ubuntu
          params:
            bump: minor
      - task: build-os-image
        file: ci/tasks/build-os-image-ubuntu-centos.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty
      - aggregate:
        - put: s3.ubuntu-trusty-os-image
          params:
            file: os-image/ubuntu-trusty.tgz
            acl: public-read
        - put: docker.ubuntu-os-image
          params:
            tag_prefix: "trusty-"
            tag: semver.os-image-ubuntu/number
            import_file: os-image/ubuntu-trusty.tgz
            tag_as_latest: true
          get_params:
            skip_download: true

  - name: build-fissile-stemcell-ubuntu-trusty
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: ci
          passed:
            - build-os-image-ubuntu-trusty
        - get: docker.ubuntu-os-image
          trigger: true
          passed:
            - build-os-image-ubuntu-trusty
        - get: git.fissile-stemcell-ubuntu
          trigger: true
        - get: semver.os-image-ubuntu
          passed:
            - build-os-image-ubuntu-trusty
      - task: setup-ubuntu-stemcell-versions
        file: ci/tasks/setup-ubuntu-stemcell-versions.yml
        input_mapping:
          src: git.fissile-stemcell-ubuntu
        params:
          DOCKER_REPOSITORY: os-image-ubuntu
      - put: docker.fissile-stemcell-ubuntu
        params:
          build: versioned-fissile-stemcell-ubuntu
          tag: versioned-fissile-stemcell-ubuntu/VERSION
        get_params:
          skip_download: true

  - name: build-os-image-opensuse-leap
    serial_groups: [os-image]
    plan:
      - aggregate:
        - get: src
          passed:
            - start-job
        - get: ci
          passed:
            - start-job
        - get: obs.fissile_base_image
        - put: semver.os-image-opensuse
          params:
            bump: minor
      - task: build
        file: ci/tasks/build-os-image-opensuse.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      opensuse
          OPERATING_SYSTEM_VERSION:   leap
      - aggregate:
        - put: s3.opensuse-leap-os-image
          params:
            file: os-image/opensuse-leap.tgz
            acl: public-read
        - put: docker.opensuse-os-image
          params:
            tag_prefix: "42.2-"
            tag: semver.os-image-opensuse/number
            import_file: os-image/opensuse-leap.tgz
            tag_as_latest: true
          get_params:
            skip_download: true
        - do:
          - task: prepare-osc
            file: ci/tasks/prepare-osc.yml
          - put: obs.fissile_base_image
            params:
              from: obs.fissile_base_image-output
              commit: { message: "latest build" }

  - name: build-fissile-stemcell-opensuse-leap
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: ci
          passed:
            - build-os-image-opensuse-leap
        - get: docker.opensuse-os-image
          trigger: true
          passed:
            - build-os-image-opensuse-leap
        - get: git.fissile-stemcell-opensuse
          trigger: true
        - get: semver.os-image-opensuse
          passed:
            - build-os-image-opensuse-leap
      - task: setup-opensuse-stemcell-versions
        file: ci/tasks/setup-opensuse-stemcell-versions.yml
        input_mapping:
          src: git.fissile-stemcell-opensuse
        params:
          DOCKER_REPOSITORY: os-image-opensuse
      - put: docker.fissile-stemcell-opensuse
        params:
          build: versioned-fissile-stemcell-opensuse
          tag: versioned-fissile-stemcell-opensuse/VERSION
        get_params:
          skip_download: true

  - name: build-os-image-sles-12
    serial_groups: [os-image]
    plan:
      - aggregate:
        - get: src
          passed:
            - start-job
        - get: ci
          passed:
            - start-job
        - put: semver.os-image-sles
          params:
            bump: minor
      - task: build
        file: ci/tasks/build-os-image-opensuse.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      sles
          OPERATING_SYSTEM_VERSION:   12
      - aggregate:
        - put: s3.sles-12-os-image
          params:
            file: os-image/sles-12.tgz
            acl: public-read


  #
  # openstack
  #

  - name: build-openstack-kvm-ubuntu-trusty
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-ubuntu-trusty]
        - get: src
          passed: [build-os-image-ubuntu-trusty]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.ubuntu-trusty-os-image
          trigger: true
          passed: [build-os-image-ubuntu-trusty]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       openstack
          HYPERVISOR: kvm
          OS_NAME:    ubuntu
          OS_VERSION: trusty
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.openstack-kvm-ubuntu-trusty-raw
          params:
            file: stemcell/*-raw.tgz
        - put: s3.openstack-kvm-ubuntu-trusty
          params:
            file: stemcell/*-go_agent.tgz


  - name: build-openstack-kvm-opensuse-leap
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-opensuse-leap]
        - get: src
          passed: [build-os-image-opensuse-leap]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.opensuse-leap-os-image
          trigger: true
          passed: [build-os-image-opensuse-leap]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       openstack
          HYPERVISOR: kvm
          OS_NAME:    opensuse
          OS_VERSION: leap
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.openstack-kvm-opensuse-leap-raw
          params:
            file: stemcell/*-raw.tgz
        - put: s3.openstack-kvm-opensuse-leap
          params:
            file: stemcell/*-go_agent.tgz


  - name: build-openstack-kvm-sles-12
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-sles-12]
        - get: src
          passed: [build-os-image-sles-12]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.sles-12-os-image
          trigger: true
          passed: [build-os-image-sles-12]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       openstack
          HYPERVISOR: kvm
          OS_NAME:    sles
          OS_VERSION: 12
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.openstack-kvm-sles-12-raw
          params:
            file: stemcell/*-raw.tgz
        - put: s3.openstack-kvm-sles-12
          params:
            file: stemcell/*-go_agent.tgz

  #
  # AWS
  #

  - name: build-aws-xen-ubuntu-trusty
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-ubuntu-trusty]
        - get: src
          passed: [build-os-image-ubuntu-trusty]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.ubuntu-trusty-os-image
          trigger: true
          passed: [build-os-image-ubuntu-trusty]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       aws
          HYPERVISOR: xen
          OS_NAME:    ubuntu
          OS_VERSION: trusty
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.aws-xen-ubuntu-trusty
          params:
            file: stemcell/*-go_agent.tgz

  - name: build-aws-xen-opensuse-leap
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-opensuse-leap]
        - get: src
          passed: [build-os-image-opensuse-leap]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.opensuse-leap-os-image
          trigger: true
          passed: [build-os-image-opensuse-leap]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       aws
          HYPERVISOR: xen
          OS_NAME:    opensuse
          OS_VERSION: leap
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.aws-xen-opensuse-leap
          params:
            file: stemcell/*-go_agent.tgz


  - name: build-aws-xen-sles-12
    serial_groups: [stemcell]
    plan:
      - aggregate:
        - get: semver.bosh-stemcell
          passed: [start-job]
        - get: ci
          passed: [build-os-image-sles-12]
        - get: src
          passed: [build-os-image-sles-12]
        - get: bosh-io-release.bosh
          passed: [start-job]
        - get: os-image
          resource: s3.sles-12-os-image
          trigger: true
          passed: [build-os-image-sles-12]
      - task: build
        file: ci/tasks/build-stemcell.yml
        privileged: true
        params:
          IAAS:       aws
          HYPERVISOR: xen
          OS_NAME:    sles
          OS_VERSION: 12
          OS_IMAGE_BUCKET: concourse-bosh-image
      - aggregate:
        - put: s3.aws-xen-sles-12
          params:
            file: stemcell/*-go_agent.tgz
resources:
  - name: ci
    type: git
    source:
      uri: git@github.com:SUSE/bosh-linux-stemcell-builder-ci.git
      branch: master
      private_key: {{github-private-key}}

  - name: src
    type: git
    source:
      uri: git@github.com:SUSE/bosh-linux-stemcell-builder.git
      branch: build_sle_stemcell
      private_key: {{github-private-key}}

  - name: git.fissile-stemcell-opensuse
    type: git
    source:
      uri: https://github.com/SUSE/fissile-stemcell-opensuse.git
      branch: 42.2

  - name: git.fissile-stemcell-ubuntu
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/fissile-stemcell-ubuntu.git
      branch: trusty

  - name: semver.os-image-opensuse
    type: semver
    source:
      driver: s3
      key: os-image-opensuse-leap-version
      bucket: concourse-bosh-image
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1
      initial_version: 0.0.0

  - name: semver.os-image-sles
    type: semver
    source:
      driver: s3
      key: os-image-sles-12-version
      bucket: concourse-bosh-image
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1
      initial_version: 0.0.0

  - name: semver.os-image-ubuntu
    type: semver
    source:
      driver: s3
      key: os-image-ubuntu-trusty-version
      bucket: concourse-bosh-image
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1
      initial_version: 0.0.0

  - name: semver.bosh-stemcell
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version
      bucket: concourse-bosh-stemcell
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1
  #
  # ubuntu-trusty
  #

  - name: s3.ubuntu-trusty-os-image
    type: s3
    source:
      bucket: concourse-bosh-image
      versioned_file: bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-ubuntu-trusty
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-trusty-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-ubuntu-trusty-raw
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.aws-xen-ubuntu-trusty
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/aws/bosh-stemcell-(.+)-aws-xen-ubuntu-trusty-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: docker.ubuntu-os-image
    type: docker-image
    source:
      repository: splatform/os-image-ubuntu
      tag: trusty
      username: {{docker-username}}
      password: {{docker-password}}

  - name: docker.fissile-stemcell-ubuntu
    type: docker-image
    source:
      repository: splatform/fissile-stemcell-ubuntu
      tag: trusty
      username: {{docker-username}}
      password: {{docker-password}}

  #
  # opensuse
  #

  - name: s3.opensuse-leap-os-image
    type: s3
    source:
      bucket: concourse-bosh-image
      versioned_file: bosh-opensuse-leap-os-image.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-opensuse-leap
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-opensuse-leap-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-opensuse-leap-raw
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-opensuse-leap-go_agent-raw.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.aws-xen-opensuse-leap
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/aws/bosh-stemcell-(.+)-aws-xen-opensuse-leap-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: docker.opensuse-os-image
    type: docker-image
    source:
      repository: splatform/os-image-opensuse
      tag: "latest"
      username: {{docker-username}}
      password: {{docker-password}}

  - name: docker.fissile-stemcell-opensuse
    type: docker-image
    source:
      repository: splatform/fissile-stemcell-opensuse
      tag: "42.2"
      username: {{docker-username}}
      password: {{docker-password}}

  - name: obs.fissile_base_image
    type: docker-open-build-service-resource
    source:
      project: home:DKarakasilis
      package: fissile_base_image
      username: {{obs-username}}
      password: {{obs-password}}

  #
  # sles
  #

  - name: s3.sles-12-os-image
    type: s3
    source:
      bucket: concourse-bosh-image
      versioned_file: bosh-sles-12-os-image.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-sles-12
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-sles-12-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.openstack-kvm-sles-12-raw
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-sles-12-go_agent-raw.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: s3.aws-xen-sles-12
    type: s3
    source:
      bucket: concourse-bosh-stemcell
      regexp: bosh-stemcell-candidate/aws/bosh-stemcell-(.+)-aws-xen-sles-12-go_agent.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  #
  # bosh releases
  #
  - name: bosh-io-release.bosh
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
