---
jobs:
  #
  # Pipeline won't automatically build if src changes, need to
  # run increase-stemcell-version manually first to increase the stemcell version
  #
  - name: increase-stemcell-version
    serial: true
    plan:
      - get: semver.bosh-stemcell
        params:
          bump: major
      - put: semver.bosh-stemcell
        params:
          file: semver.bosh-stemcell/number

  - name: build-os-image-opensuse-leap
    serial_groups: [opensuse]
    plan:
      - aggregate:
        - get: src
        - get: ci
        - put: semver.os-image-opensuse
          params:
            bump: minor
        - get: lftp.os-image-opensuse
          trigger: true
      - task: build
        file: ci/tasks/build-os-image-opensuse.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      opensuse
          OPERATING_SYSTEM_VERSION:   leap
      - aggregate:
        - put: s3.opensuse-leap-os-image
          params:
            file: os-image/opensuse-leap.tgz
            acl: public-read
        - put: docker.opensuse-os-image
          params:
            tag_prefix: "42.2-"
            tag: semver.os-image-opensuse/number
            import_file: os-image/opensuse-leap.tgz
            tag_as_latest: true
          get_params:
            skip_download: true

  - name: build-fissile-stemcell-opensuse-leap
    serial_groups: [opensuse]
    plan:
      - aggregate:
        - get: ci
        - get: docker.opensuse-os-image
          trigger: true
        - get: git.fissile-stemcell-opensuse
          trigger: true
        - get: semver.os-image-opensuse
      - task: setup-opensuse-stemcell-versions
        file: ci/tasks/setup-opensuse-stemcell-versions.yml
        input_mapping:
          src: git.fissile-stemcell-opensuse
        params:
          DOCKER_REPOSITORY: os-image-opensuse
      - put: docker.fissile-stemcell-opensuse
        params:
          build: versioned-fissile-stemcell-opensuse
          tag: versioned-fissile-stemcell-opensuse/VERSION
          build_args:
            base_image: splatform/os-image-opensuse:42.2
            configgin_version: 0.14.1
        get_params:
          skip_download: true

resource_types:
- name: lftp-resource
  type: docker-image
  source:
    repository: machinerytool/concourse-lftp-resource
    tag: latest

resources:
  - name: lftp.os-image-opensuse
    type: lftp-resource
    source:
      url: https://download.opensuse.org/repositories/Cloud:/Platform:/os-image:/openSUSE/images/
      regexp: Leap-42.1.x86_64-1.42.2-Build(.*).tbz

  - name: ci
    type: git
    source:
      uri: git@github.com:SUSE/bosh-linux-stemcell-builder-ci.git
      branch: alexh/opensuse-42.2-build
      private_key: {{github-private-key}}

  - name: src
    type: git
    source:
      uri: git@github.com:SUSE/bosh-linux-stemcell-builder.git
      branch: opensuse_stemcell
      private_key: {{github-private-key}}

  - name: git.fissile-stemcell-opensuse
    type: git
    source:
      uri: https://github.com/SUSE/fissile-stemcell-openSUSE.git
      branch: 42.2

  - name: semver.os-image-opensuse
    type: semver
    source:
      driver: s3
      key: os-image-opensuse-leap-version
      bucket: concourse-bosh-image
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1
      initial_version: 0.0.0

  - name: semver.bosh-stemcell
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version
      bucket: concourse-bosh-stemcell
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  #
  # opensuse
  #

  - name: s3.opensuse-leap-os-image
    type: s3
    source:
      bucket: concourse-bosh-image
      versioned_file: bosh-opensuse-leap-os-image.tgz
      access_key_id: {{aws-access-key}}
      secret_access_key: {{aws-secret-key}}
      region_name: eu-central-1

  - name: docker.opensuse-os-image
    type: docker-image
    source:
      repository: splatform/os-image-opensuse
      username: {{docker-username}}
      password: {{docker-password}}

  - name: docker.fissile-stemcell-opensuse
    type: docker-image
    source:
      repository: splatform/fissile-stemcell-opensuse
      username: {{docker-username}}
      password: {{docker-password}}

  #
  # bosh releases
  #
  # - name: docker.opensuse
  #   type: docker-image
  #   source:
  #     repository: opensuse
  #     tag: leap

  # - name: docker.splatform-suse-os-image-stemcell-builder
  #   type: docker-image
  #   source:
  #     repository: splatform/suse-os-image-stemcell-builder
  #     tag: latest
  #     username: {{docker-username}}
  #     password: {{docker-password}}
