---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: src
  - name: ci
  - name: semver.bosh-stemcell

outputs:
  - name: stemcell

run:
  path: ci/tasks/build-stemcell.sh

params:
  IAAS:         replace-me
  HYPERVISOR:   replace-me
  OS_NAME:      replace-me
  OS_VERSION:   replace-me
  OS_IMAGE_BUCKET: ""
  BOSHIO_TOKEN: ""
