---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: splatform/suse-os-image-stemcell-builder

inputs:
  - name: suse-build-opensuse-task
  - name: bosh-linux-stemcell-builder

outputs:
- name: os-image

run:
  path: suse-build-opensuse-task/ci/pipelines/bosh-stemcell-master/os-images/build-opensuse-task.sh

params:
  OPERATING_SYSTEM_NAME:      replace-me
  OPERATING_SYSTEM_VERSION:   replace-me
