---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: suse-ci
  - name: bosh-linux-stemcell-builder
  - name: version
  - name: stemcells-index
  - name: os-image

outputs:
  - name: stemcell
  - name: stemcells-index
    path: stemcells-index-output

run:
  path: suse-ci/tasks/build.sh

params:
  IAAS:         replace-me
  HYPERVISOR:   replace-me
  OS_NAME:      replace-me
  OS_VERSION:   replace-me
