---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinerytool/suse-os-image-stemcell-builder-test


inputs:
  - name: src
  - name: ci

outputs:
  - name: os-image

run:
  path: ci/tasks/build-os-image-opensuse.sh

params:
  OPERATING_SYSTEM_NAME:      replace-me
  OPERATING_SYSTEM_VERSION:   replace-me
