---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: machinerytool/suse-os-image-stemcell-builder


inputs:
  - name: src
  - name: ci

outputs:
  - name: os-image

run:
  path: ci/ci/pipelines/bosh-os-images/tasks/build.sh

params:
  OPERATING_SYSTEM_NAME:      replace-me
  OPERATING_SYSTEM_VERSION:   replace-me
