---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: suse-ci
  - name: suse-cf
  - name: environment
  - name: bosh-linux-stemcell-builder
  - name: bosh-cli
  - name: bosh-deployment
  - name: stemcell

outputs:
  - name: director-state

run:
  path: suse-ci/tasks/deploy-director.sh
