---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
- name: ci
- name: semver.os-image-opensuse
- name: git.fissile-stemcell-opensuse

input_mapping:
- src: git.fissile-stemcell-opensuse

outputs:
- name: versioned-fissile-stemcell-opensuse

run:
  path: ci/tasks/setup-opensuse-stemcell-versions.sh

params:
  DOCKER_REPOSITORY: replace-me
