---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
- name: ci
- name: semver.ubuntu-stemcell
- name: git.fissile-stemcell-ubuntu

outputs:
- name: versioned-fissile-stemcell-ubuntu

run:
  path: ci/tasks/setup-ubuntu-stemcell-versions.sh
