---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
- name: environment
- name: bosh-src
- name: suse-ci
- name: bosh-cli
- name: bosh-deployment
- name: bosh-release
- name: stemcell

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""

outputs:
- name: director-state

run:
  path: suse-ci/sles-aws/tasks/deploy-director.sh
