---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: suse-ci
  - name: bosh-cli
  - name: director-state
  - name: environment

run:
  path: suse-ci/sles-aws/tasks/destroy-director.sh
