---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: environment
  - name: director-state
  - name: suse-ci

params:
  STEMCELL_NAME: null

outputs:
  - name: bats-config

run:
  path: suse-ci/sles-aws/tasks/prepare-bats-config.sh
