---

shared:
  - tags: &tags ['eng-provo']

jobs:
  - name: build-ubuntu-trusty
    serial_groups: [ubuntu]
    plan:
      - get: bosh-linux-stemcell-builder
        trigger: true
      - task: build
        tags: *tags
        file: bosh-linux-stemcell-builder/ci/os-images/tasks/build.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty
      - put: ubuntu-trusty-tarball
        params:
          file: os-image/ubuntu-trusty.tgz
          acl: public-read

  - name: build-opensuse-leap
    plan:
      - get: lftp.os-image-opensuse
        trigger: true
      - get: bosh-linux-stemcell-builder
        trigger: true
      - task: build
        tags: *tags
        file: bosh-linux-stemcell-builder/ci/os-images/tasks/build-opensuse.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      opensuse
          OPERATING_SYSTEM_VERSION:   leap
          TARGET_USER:                user
      - put: opensuse-leap-os-image
        params:
          file: os-image/opensuse-leap.tgz
          acl: public-read

resource_types:
- name: lftp-resource
  type: docker-image
  source:
    repository: machinerytool/concourse-lftp-resource
    tag: latest

resources:
  - name: lftp.os-image-opensuse
    type: lftp-resource
    source:
      url: http://download.opensuse.org/repositories/Cloud:/Platform:/os-image:/openSUSE/images/
      regexp: Leap-42.3.x86_64-1.42.3-Build(.*).tbz

  - name: bosh-linux-stemcell-builder
    type: git
    source:
      submodules: all
      uri: {{repo}}
      branch: {{branch}}

  #
  # ubuntu-trusty
  #

  - name: ubuntu-trusty-tarball
    type: s3
    source:
      bucket: {{osimage-aws-bucket}}
      versioned_file: ((osimage-aws-directory))/bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{osimage-aws-access-key}}
      secret_access_key: {{osimage-aws-secret-key}}
      region_name: {{osimage-aws-region}}

  #
  # opensuse
  #

  - name: opensuse-leap-os-image
    type: s3
    source:
      bucket: {{osimage-aws-bucket}}
      versioned_file: ((osimage-aws-directory))/bosh-opensuse-leap-os-image.tgz
      access_key_id: {{osimage-aws-access-key}}
      secret_access_key: {{osimage-aws-secret-key}}
      region_name: {{osimage-aws-region}}
