networks:
- name: ((env_name))
  type: manual
  subnets:
  - range: ((internal_cidr))
    reserved:	((reserved_range))
    gateway: ((internal_gw))
    dns: ((net_dns))
    cloud_properties:
      net_id: ((net_id))
      security_groups:
      - bosh-concourse
    azs: [default_az]
